field: eaa35a80-8a4a-4899-a262-71fe40fb097f
fieldLayouts:
  2a14dace-46bb-4e74-b262-496c09450164:
    tabs:
      -
        elements:
          -
            fieldUid: 5a46c026-88d2-4f8c-aaae-697ca56c7763
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 581c61be-e30c-4efe-991a-a77703bc401f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  581c61be-e30c-4efe-991a-a77703bc401f:
    contentColumnType: text
    fieldGroup: null
    handle: iconName
    instructions: ''
    name: 'Icon Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5a46c026-88d2-4f8c-aaae-697ca56c7763:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: listItem
name: 'List Item'
sortOrder: 1
