childBlocks: ''
field: 95bb7f79-d11f-4e9d-aa81-e64600ff3f53
fieldLayouts:
  3748c81f-ce93-4390-8658-0808f90cb064:
    tabs:
      -
        fields:
          1a270472-7b9a-4b1b-b79e-e10cd6fe0461:
            required: false
            sortOrder: 2
          6615c6a9-2999-40bf-8b0f-2aafda51da88:
            required: false
            sortOrder: 4
          c9ae56dd-0d2d-48db-9a8e-195679072eaf:
            required: false
            sortOrder: 1
          e74bdc1e-2c13-4db8-bd47-df4726f13ee7:
            required: false
            sortOrder: 0
          e934635a-7522-4ca2-8fea-8e0eedd5537f:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
      -
        fields:
          c66e6c0a-b52a-4675-ad32-e6d88ce12fb1:
            required: false
            sortOrder: 0
          e3f3af88-6d54-472f-a1f6-52a81a2f443a:
            required: false
            sortOrder: 1
        name: Code
        sortOrder: 2
handle: banner
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Banner
sortOrder: 3
topLevel: true
