childBlocks: ''
field: 95bb7f79-d11f-4e9d-aa81-e64600ff3f53
fieldLayouts:
  ec91ba1a-91d8-409f-87a5-6192433e8aee:
    tabs:
      -
        fields:
          1a270472-7b9a-4b1b-b79e-e10cd6fe0461:
            required: false
            sortOrder: 1
          3eddcfc3-baeb-44a9-8547-77036da24db3:
            required: false
            sortOrder: 3
          94106057-1109-465b-b44a-2669751a90e7:
            required: false
            sortOrder: 2
          c9ae56dd-0d2d-48db-9a8e-195679072eaf:
            required: false
            sortOrder: 0
        name: Content
        sortOrder: 1
      -
        fields:
          c66e6c0a-b52a-4675-ad32-e6d88ce12fb1:
            required: false
            sortOrder: 0
          e3f3af88-6d54-472f-a1f6-52a81a2f443a:
            required: false
            sortOrder: 1
        name: Code
        sortOrder: 2
handle: form
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Form
sortOrder: 7
topLevel: true
