childBlocks: ''
field: 95bb7f79-d11f-4e9d-aa81-e64600ff3f53
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: c9ae56dd-0d2d-48db-9a8e-195679072eaf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a270472-7b9a-4b1b-b79e-e10cd6fe0461
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0d3b33b-126e-45c3-a3b8-eac104153c6c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c66e6c0a-b52a-4675-ad32-e6d88ce12fb1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e3f3af88-6d54-472f-a1f6-52a81a2f443a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Code
        sortOrder: 2
handle: gallery
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Gallery
sortOrder: 2
topLevel: true
