childBlocks: ''
field: 95bb7f79-d11f-4e9d-aa81-e64600ff3f53
fieldLayouts:
  b18d1441-5f37-40d5-b467-ff39eb3ee0ce:
    tabs:
      -
        fields:
          1a270472-7b9a-4b1b-b79e-e10cd6fe0461:
            required: false
            sortOrder: 1
          59d46f76-d3e9-49ae-88a2-f0b37b519ffc:
            required: false
            sortOrder: 2
          c9ae56dd-0d2d-48db-9a8e-195679072eaf:
            required: false
            sortOrder: 0
        name: Content
        sortOrder: 1
      -
        fields:
          c66e6c0a-b52a-4675-ad32-e6d88ce12fb1:
            required: false
            sortOrder: 0
          e3f3af88-6d54-472f-a1f6-52a81a2f443a:
            required: false
            sortOrder: 1
        name: Code
        sortOrder: 2
handle: legal
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Legal
sortOrder: 9
topLevel: true
