fieldLayouts:
  695a31c1-f4c8-40c1-a0db-2f5106babaa3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: vectorsDigitalOcean
hasUrls: true
name: 'Vectors - Digital Ocean'
settings:
  bucket: elev8stud.io
  contentDisposition: inline
  endpoint: $DO_ENDPOINT
  expires: ''
  keyId: $DO_KEY_ID
  region: ams3
  secret: $DO_ACCESS_KEY
  subfolder: vectors
sortOrder: 4
type: vaersaagod\dospaces\Volume
url: '@assetUrl'
