contentColumnType: string
fieldGroup: 62b76306-9f87-4885-af7d-16855c915296
handle: blocks
instructions: ''
name: Blocks
searchable: false
settings:
  maxBlocks: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
