contentColumnType: text
fieldGroup: 62b76306-9f87-4885-af7d-16855c915296
handle: code
instructions: ''
name: Code
searchable: false
settings:
  mode: htmlmixed
translationKeyFormat: null
translationMethod: none
type: luwes\codemirror\fields\CodeMirrorField
