contentColumnType: string
fieldGroup: 62b76306-9f87-4885-af7d-16855c915296
handle: formSelect
instructions: ''
name: 'Form Select'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - contact
        -
          - value
          - contact
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
