contentColumnType: string
fieldGroup: 62b76306-9f87-4885-af7d-16855c915296
handle: iconList
instructions: ''
name: 'Icon List'
searchable: false
settings:
  contentTable: '{{%matrixcontent_iconlist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
