contentColumnType: text
fieldGroup: 62b76306-9f87-4885-af7d-16855c915296
handle: sectionId
instructions: ''
name: 'Section Id'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
