contentColumnType: text
fieldGroup: 62b76306-9f87-4885-af7d-16855c915296
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  description: 'Web development studio based in Bristol and South West England. We build uniquely crafted, bespoke and user friendly websites. We develop web based applications using React.js and Laravel. '
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage:
    - '630'
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '1'
        -
          - template
          - 'Web Development in Bristol | {{ siteName }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: none
type: ether\seo\fields\SeoField
