fieldLayouts:
  baec1677-f510-4091-98cb-f108d270c3d6:
    tabs:
      -
        elements:
          -
            fieldUid: 1dd8091c-17b6-4c39-9aa2-baa480d09ef3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d677cc2f-c724-4544-bfce-7247d4706699
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3eddcfc3-baeb-44a9-8547-77036da24db3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: footer
name: Footer
