fieldLayouts:
  e10bc521-3cf6-4152-a367-8acb6f4fd4c4:
    tabs:
      -
        elements:
          -
            fieldUid: 1dd8091c-17b6-4c39-9aa2-baa480d09ef3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: navigation
name: Navigation
