enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  5a817c01-23fa-4c5f-a9eb-4e46538c444c:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
